# Makefile per la compilazione del progetto LaTeX
# Creato lun 13 giu 2016, 15.28.42, CEST

.PHONY: alldocuments reference 

alldocuments: 
	pdflatex reference.tex
	rm -f *.aux *.log *.out

reference:
	pdflatex reference.tex
	rm -f *.aux *.log *.out

# Fine del Makefile
